export const backgrounds = [
  "Beauty kanji.png",
  "Circle Blue.png",
  "Circle Red.png",
  "Colouring Kanji.png",
  "Crysanthemum.png",
  "Dragon Kanji.png",
  "Dragon.png",
  "Enjoy Kanji.png",
  "Flower petals.png",
  "Glad Kanji.png",
  "Leaves.png",
  "Love Kanji.png",
  "Luck Kanji.png",
  "Pink Spray.png",
  "Plant.png",
  "Red Flowers.png",
  "Rose.png",
  "Splash.png",
  "Water Colour.png",
  "Weed Kanji.png",
];
